let actionType = {
  CURRENT_SCREEN: 'CURRENT_SCREEN',
  SET_LOGIN_DATA: 'SET_LOGIN_DATA',
  SET_REGISTER_DATA: 'SET_REGISTER_DATA',
  SET_PROFIL_DATA: 'SET_PROFIL_DATA',
  SET_OTP_DATA: 'SET_OTP_DATA',
  SET_OTPID_DATA: 'SET_OTPID_DATA',
  SET_PROFIL_PICTURE: 'SET_PROFIL_PICTURE',
  SET_DASHBOARD_DATA: 'SET_DASHBOARD_DATA',
  LOGOUT: 'LOGOUT',
  TOGGLE_LOADER: 'TOGGLE_LOADER',
  SET_HOSPITAL_LIST: 'SET_HOSPITAL_LIST',
  SET_DEPARTMENT_LIST: 'SET_DEPARTMENT_LIST',
  SET_DOCTORS_LIST: 'SET_DOCTORS_LIST',
  SET_BOOK_NOW_DATA: 'SET_BOOK_NOW_DATA',
  SET_WAITING_ROOM_DATA: 'SET_WAITING_ROOM_DATA',
  SET_MYAPPOINTMENT_DATA: 'SET_MYAPPOINTMENT_DATA',
  SET_INFLIGHTDATA_DATA: 'SET_INFLIGHTDATA_DATA',
  SET_DEPARTMENTLIST_DATA: 'SET_DEPARTMENTLIST_DATA',
  SET_AVAILABLESLOTS_DATA: 'SET_AVAILABLESLOTS_DATA',
  SET_DOCTORDETAILS_DATA: 'SET_DOCTORDETAILS_DATA',
};

module.exports = actionType;
