const { default: Rating } = require('../screens/dashboard/auditQuestions');

let Strings = {
  MediPulse:'MediPulse',
  BookNow:'Book Now',
  LatestEvent:'Latest Event',
  alert: {
    pass_reset:
      'Your password has been successfully reset Click below to sign in magically.',
    alert_text: 'Alert',
  },
  drawer:{
    Patient:'Patient',
    Notifications:'Notifications',
    Setting:'Setting',
    Language:'Language',
    ChangePassword:'Change Password',
    Logout:'Logout'
  },
  home:{
    UpcomingAppointment:'Upcoming Appointment',
    Within24Hr:'Within 24Hr',
    BookNowCard:'Book an Appointment',
    HospitalVisits:'Hospital Visits',
    HealthChecks:'Health Checks',
    Vaccinations:'Vaccinations',
    Documents:'Documents',
  },
  appoiments:{
    title:'My Appointments',
    UpcomingAppointment:'Upcoming Appointment',
    NoAppointment:'No active Appointment',
    Workflow:'Workflow',
    Xray:'Xray',
    Sonography:'Sonography',
    LipidProfile:'Lipid Profile',
    BloodSugar:'Blood Sugar',
    ApptNo:'Appt. No.:',
    Status:'Status:',
  },
  documents:{
    NoDocuments:'No Documents Available',
    Share:'Share',
    SelectedDocuments:'Selected Documents',
    SearchDocument:'Search Document'
  },
  visits:{
    Visits:'Visits',
    NoVisits:'No Visits Available',
  },
  profile:{
     title:'My Profile',
     YourInsurancenumber:'Your Insurance number',
     Allergies:'Allergies',
     BloodType:'Blood Type',
     BMI:'BMI',
     Pulse:'Pulse',
     HeartRate:'Heart Rate',
     BP:'BP',
     Tobacco:'Tobacco',
     Alcohol:'Alcohol',
     NotAvailable:'Not Available',
  },
  tabNavigater:{
    Home:'Home',
    Appointments:'Appointments',
    Documents:'Documents',
    Visits:'Visits',
    Profile:'Profile',
    // Profile:'Profile',
  },



  HIPPA_KEY: '',
  permission_text: {
    permission_decline: 'User declined messaging permissions :(',
    allow_text: 'Please Allow to procced further',
    not_allow: "Don't Allow",
    allow: 'Allow',
    logout_text: 'Are you sure you want to logout?',
    yes_text: 'Yes',
    no_text: 'No',
    exit_txt: 'Are you sure you want to exit the application?',
    location_denied:
      'You have denied request to access location. Click here to enable LOCATION permission from Settings.',
  },
  

  auth: {
    welcome: 'Welcome to Ultimate Security!',
    continue: 'Sign in to Continue',
    no_account: 'Are you a new user?',
    sign_up: 'Sign Up',
    sign_in: 'Login',
    keep_in: 'Keep me signed in',
    enter_pass: ' Enter Password',
    forget: 'Forget Password ?',
    set_pass: 'Set New Password',
    auth: 'Two factor authentication ',
    code_sent: 'Verification Code Sent on',
    continue: 'Continue',
    cancel: 'Cancel',
    reset: 'Reset password',
    enterOtpTxt: 'Enter OTP',
    not_receive: 'Did not receive code?',
    resend: 'Resend Code',
    already_acount: 'Already have an account?',
    signUp_heading: 'Enter your details for creating account. Thanks',
    personal_details: 'Personal Details',
    add_emergnecy: 'Add Emergency Contact',
    save: 'Save & Next',
    profile: 'Profile Creation',
    login: 'Login',
    enter_email: 'Enter Email',
    register: 'Register',
    signUp: 'SignUp',
    enter_name: 'Enter Name',
    enter_pass: 'Enter Password',
    enter_currentPass: 'Enter Current Password',
    enter_newPass: 'Enter New Password',
    enter_confirmPass: 'Confirm Password',
    enter_address: 'Enter Address',
    enter_phone: 'ENter Mobile Number',
    enter_cnfrmPass: 'Enter Confirm Password',
    exitUser: 'Existing User?',
    forgetText:
      "Please enter your email address and we'll send you instructions on how to reset your password",
    otpText: 'Please enter your 6 digit OTP you have received on your email.',
    otp: 'OTP',
    enter_description: 'Add Description'
  },
  form: {
    phone: 'Phone Number',
    mobile: 'Mobile Number',
    pass: 'Password',
    newPass: 'New Password',
    confirmPass: 'Confirm Passowrd',
    email: 'E-mail',
    confirm: 'Confirm Password',
    fname: 'Full Name',
    gender: 'Gender',
    dob: 'Date of Birth',
    blood_grp: 'Blood Group',
    martial: 'Marital Status',
    m_name: 'Middle Name',
    l_name: 'Last Name',
    age: 'Age',
    address: 'Address',
    neighbor: 'Neighborhood',
    country: 'Country',
    Region: 'Region',
    Province: 'Province',
    Department: 'Department',
    City: 'City',
    Village: 'Village',
    Pincode: 'Pincode',
    name: 'Name',
    relationship: 'Relationship',
    currentPass: 'Current Password',
    newPass: 'New Password',
    confirmPass: 'Confirm Password',
  },
  validation: {
    diff_pass:
      'Your new password must be different to previously used passwords.',
    enter_code: 'Enter 4 digit code',
    invalid_email: 'Please enter valid email address',
    invalid_email: 'Please enter valid contact number',
    missing_email: 'Email is missing',
    missing_mobileNo: 'Contact number is missing',
    missing_address: 'Address is missing',
    missing_city: 'City is missing',
    missing_state: 'State is missing',
    missing_insuranceNo: 'Insurance Number is missing',
    missing_insuranceProvider: 'Insurance Provider is missing',

    missing_firstName: 'First Name is missing',
    missing_lastname: 'Last Name is missing',
    invalid_otp: 'Invalid Otp',
    valid_password: 'Please enter valid password',
    match_length_password: 'Please ensure that your password contains a minimum of 8 characters.',
    match_password: 'Password and confirm password do not match',
    missing_password: 'Password is missing',
    empty_fields: 'Please fill all the fields to continue.',
    missing_currentpassword: 'Current Password is missing',
    missing_newPassword: 'New Password is missing',
    missing_confirmPassword: 'Confirm Password is missing',
    match_Pass: 'Your New Password & Current Password is not match',
    uploadImage: 'Please upload Image',

    allField: 'Please add all fields',
    missing_sig: 'Please add signature',
   

  },
  customAlert: {
    title: 'Alert',
    button: 'Ok',
  },
  dashboard: {
    search: 'Search',
    dash_title: 'Home',
    mySites: 'My Sites',
    mySchedules: 'My Schedules',
    myVisit: 'My Visits',
    profile: 'Profile',
    name: 'Name: ',
    address: 'Address',
    contact: 'Contact',
    area: 'Site Area',
    editProfile: 'Edit Profile',
    updateprofile: 'Update Profile',
    scan: 'Qr Scan',
    notification: 'Notification',
    alarm: 'Alarm',
    adHoc: 'AD-HOC',
    task: 'My Task',
    training: 'Training',
    auditForm: 'Audit Form',
    dynamicForm: 'Dynamic Form',
    induction: 'Induction',
    document: 'Document',
    uploadFile: 'Upload Your File',
    pdfText: 'Upload PDF, DOC,JPEJ & EXCEL only',
    uploadText: 'Upload',
    cancel: 'Cancel',
    submit: 'Submit',
    uploadImageFrom: 'Upload Photo',
    camera: 'Camera',
    gallery: 'Gallery',
    signature: 'Signature',
    startVisit: 'Start Visit',
    endVisit: 'End Visit',
    location: 'Location',
    siteType: 'Site Type',
    uploadSignture: 'Upload Signature',
    expDate: 'Document Expiry Date * ',
    license: 'License',
    setting: 'Setting',
    editProfile: 'Edit Profile',
    changePass: 'Change Password',
    logout: 'Logout',
    logoutText: 'Do you want to logout?',
    no: 'No',
    yes: 'Yes',
    ChangePassword: 'ChangePassword',
    airport: 'Airport',
    checkout: 'Checkout',
    countinueWithScan: 'Continue With Scan',
    countinueWithoutScan: 'Continue Without Scan',
    uploadphoto: 'Upload Photo',
    enterText: 'Please Add some description why you selecting No',
    addPhoto: 'Add Photo',
    duration: 'Duration:',
    startTime: 'Start Time:',
    endTime: 'End Time:',
    siteStatus: 'Site Status:',
    trainigQuestions: 'Training Questions',
    inductionQuestions: 'Induction Questions',
    schedule: "Schedule List",
    siteName: 'Site Name',
    contactPerson: 'Contact Person',
    contactNum: 'Contact Number',
    serviceName: 'Service Name',
    siteInformation: 'Site Information',
    mySchedule: 'My Schedules',
    occurrence: 'Occurrence',
    scheduleName : 'Schedule Name: ',
    date: 'Date: '

  },
  server: {
    server_is_not_reachable:
      'The server is not reachable right now, sorry for inconvenience.',
    error: 'Error',
  },
  notification: {
    decline: 'Decline',
    accept: 'Accept',
  },
  DB_NAME: 'UserDatabase.db',
};
module.exports = Strings;
