let API_URL = {
  LOGIN: 'user/login',
  REGISTER: 'user/register',
  PROFILEUPDATE: 'user/profile',
  GETPROFILE: 'user/profile',
  SENDOTP: 'user/forgetPassword',
  VALIDATEOTP: 'user/verifyOTP?otp=',
  VALIDATEOTPREGISTER: 'user/verifyOTPOnEmail?otp=',
  RESETPASSWORD: 'user/updatePassword?userId=',
  CHANGEPASSWORD: 'user/changePassword',
  PROFILEPICTURE: 'user/profile/picture',
  GETDASHBOARDDATA: 'user/dashboard',
  GETHOSPITALSLIST: 'appointment/hospitals',
  GETDEPARTMENTLIST: 'department/availability?hospitalId=',
  SEARCHDOCTORLIST: 'user/staff/availability',
  BOOKAPPOINTMENT: 'appointment/slot/',
  RESCHEDULEAPPOINTMENT: 'appointment/slot/rescheduleAppointment/',
  CANCELAPPOINTMENT: 'appointment/slot/cancel/',
  OUTFROMWAITING: 'waitingRoom/optOut',
  ENROLLWAITINGROOM: 'waitingRoom/enroll',
  MYAPPOINTMENTLIST: 'user/my-appointments',
  INFLIGHTDATA: 'examine/inFlightPatient',
  SEARCHHOSPITALLIST: 'appointment/hospitals?search=',
  SEARCHDEPARTMENTLIST: 'appointment/departmentlList?search=',
  SEARCHDOCUMENTSLIST: 'examine/searchExaminationDocs?search=',
  GETAVAILABLESLOTS: 'appointment/slots/',
  GETDOCTORDETAILS: 'user/getDoctorById/',
  GETVISITDETAILS: 'examine/getVisitsDataByID?visitId=',
  DOCTORLIST: 'user/staff/getDoctorsList',
  DOWNLOADDOC: 'examine/downloadFile?s3Key=',
  SHAREDOCUMENT: 'examine/shareDocumentWithDoctor?doctorId=',


};
module.exports = API_URL;
